{{- if .Values.airflow.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "main.fullname" . }}-airflow-web
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/timeout: 600s
spec:
  {{- if .Values.airflow.route.host }}
  host: {{ .Values.airflow.route.host }}
  {{- end }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: airflow-webserver
{{- end }}
