name: Build MongoDB image

on:
  workflow_dispatch:
  schedule:
  - cron: 0 3 * * *

env:
  GITHUB_REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-mongodb:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@064fe7f3312418007dea2b49a19844a9ee378f49

    - name: Get MongoDB version
      run: |
        VERSION=$(docker run --rm --entrypoint mongod docker.io/bitnamisecure/mongodb:latest --version \
          | grep "db version" | awk '{print substr($3,2)}')
        echo "MongoDB version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create Dockerfile
      run: |
        cat > Dockerfile <<'EOF'
        FROM docker.io/bitnamisecure/mongodb:latest
        EOF

    - name: Build and Push Docker image
      uses: egose/actions/docker-build-push@b3ab7cd7a5282c03badcbcf3ac33c92b74b744aa
      with:
        registry-url: ${{ env.GITHUB_REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        image-name: bcgov/bitnami-mongodb
        docker-context: .
        docker-file: Dockerfile
        metadata-tags: |
          latest
          ${{ env.VERSION }}
